apiVersion: v1
kind: Secret
metadata:
  name: mtr-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJtdHIuZXh0ZXJuYWwub3RjLnRlbGVrb21jbG91ZC5jb20iOiB7CiAgICAgICJhdXRoIjogIllXSmhiV0p2YVN0aVlXMWlhWGc2VjFWQ1JWZExRa1E0T1U1RE9FWlpVMDVHTjFwS05FTkxSVWRUTlUwME5USk9TRU5hVFZaYVRVZFRWVTFJUzFOT01WWXdXVXN3VDBORk5sRktWVWcwUXc9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson