apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: v1
kind: Namespace
metadata:
  name: app2
---
apiVersion: v1
kind: Namespace
metadata:
  name: app3
---
apiVersion: v1
kind: Namespace
metadata:
  name: app4

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-test-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: hook-test-script
          image: centos
          command:
            - echo "This is a hook script test"
      restartPolicy: Never
  backoffLimit: 2