apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace2
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace3
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace4

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-test-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: internal-kubectl
      containers:
        - name: hook-test-script
          image: mtr.external.otc.telekomcloud.com/abamboi/alpine:k8s_1.14.6
          command:
            - "kubectl"
          args:
            - "get"
            - "ns"
      imagePullSecrets:
        - name: mtr-pull-secret
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: mtr-pull-secret
  namespace: argocd
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJtdHIuZXh0ZXJuYWwub3RjLnRlbGVrb21jbG91ZC5jb20iOiB7CiAgICAgICJhdXRoIjogIllXSmhiV0p2YVN0aVlXMWlhWGc2VjFWQ1JWZExRa1E0T1U1RE9FWlpVMDVHTjFwS05FTkxSVWRUTlUwME5USk9TRU5hVFZaYVRVZFRWVTFJUzFOT01WWXdXVXN3VDBORk5sRktWVWcwUXc9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secrets-for-ns
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - secrets
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secret-for-ns
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: create-secrets-for-ns
  apiGroup: rbac.authorization.k8s.io
